### ISSUE TITLE
CHRONI on iPhone

### ISSUE THREAD

**Issue by noahmclean** [CIRDLES/CHRONI#82]
Hi Team,

I downloaded CHRONI on my iPhone from the Apple App Store.  I can log in to Geochron with my credentials and then type an IGSN into the Download tab, but I can't open that aliquot and view the data.  The help on the app points to your cirdles.org page, which says that the current version of CHRONI (version 1.0.1) only works on Android devices.  Is this out of date?  Why would it be available on the Apple App Store if the app doesn't work?  

There is no version listed on the About tab in the app, so I can't confirm that this documentation applies to the app that I downloaded.  Also, the first step in the cirdles.org documentation instructs that I download the most recent CHRONI APK from your releases page on Github, but there are no releases on Github.

Best wishes,
Noah

**Comment by gabriellecozart** [comment]
Hello Noah,

Thank you for submitting an issue! Yes the documentation on the website is out of date and I will notify the web team immediately about the versioning and the apk from GitHub. We will also add the versioning to the about page. This is CHRONI version 2 on the App Store so no worries.

As for the IGSN, are you getting a successful toast notification saying it was downloaded?

**Comment by noahmclean** [comment]
Hi Gabrielle,

Yes, I'm getting a successful notification that my aliquot was downloaded.  How do I open it?  There doesn't seem to be an 'Open' button anywere... your (v.1.0.1) documentation mentions an 'Open' button on the Chroni main screen, but I don't see a main screen, and it's not in the menu.  Here's a screen shot: [https://www.dropbox.com/s/8abn11ce3kkkv4u/2017-09-18%2014.10.20.png?dl=0](https://www.dropbox.com/s/8abn11ce3kkkv4u/2017-09-18%2014.10.20.png?dl=0)

Question: have you tried CHRONI on an iPhone?  Does it work?

**Comment by gabriellecozart** [comment]
Sorry it's a user experience error it seems. We are in the process of redesigning the interface. Go to the side menu and click on the 'Manage Report Table' option. It will take you to a screen where you can choose which aliquot and which report settings to open. On the aliquot section click the edit button on the right side and select the aliquot you downloaded. You can keep the report settings the same for now and then click the 'View Report' button. The table will appear better in landscape.

We are still working on designing the app and we really appreciate your feedback so we can make it better and more intuitive. I how I cleared some confusion.

**Comment by noahmclean** [comment]
Ah, great, thanks for that.  I can see that and make it work.  Next I'll try exporting some report settings.  Cheers!
